LDLIBS += -lcs50
all:
	gcc meow.c C:\CS50X\cs50.c -o meow -std=c99"
	gcc meow_function.c C:\CS50X\cs50.c -o meow_function -std=c99"
	gcc my_meow_function.c C:\CS50X\cs50.c -o my_meow_function -std=c99"